---
swagger: "2.0"
info:
  version: "1.0"
  title: "ObservabilityAPI"
host: "macbook-pro-de-stephane.home:5555"
basePath: "/observability"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /hello:
    get:
      operationId: "hello_GET_1"
      parameters:
      - name: "name"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/hello_GET_response"
        "401":
          description: "Access Denied"
  /message:
    get:
      operationId: "message_GET_2"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/request"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/message_GET_response"
        "401":
          description: "Access Denied"
  /fibonacci:
    get:
      operationId: "fibonacci_GET_3"
      parameters:
      - name: "n"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/fibonacci_GET_response"
        "401":
          description: "Access Denied"
  /fibonacci/async:
    get:
      operationId: "fibonacciasync_GET_4"
      parameters:
      - name: "n"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/fibonacciasync_GET_response"
        "401":
          description: "Access Denied"
  /message/async:
    post:
      operationId: "messageasync_POST_5"
      consumes:
      - "application/x-www-form-urlencoded"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/request"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/messageasync_POST_response"
        "401":
          description: "Access Denied"
  /sleep:
    get:
      operationId: "sleep_GET_6"
      parameters:
      - name: "delayMillis"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Access Denied"
  /memory:
    get:
      operationId: "memory_GET_7"
      parameters:
      - name: "memoryMb"
        in: "query"
        required: true
        type: "string"
      - name: "delayMillis"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Access Denied"
definitions:
  message_GET_response:
    type: "object"
    required:
    - "response"
    properties:
      response:
        $ref: "#/definitions/response"
  request:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "array"
        items:
          type: "string"
  messageasync_POST_response:
    type: "object"
    required:
    - "response"
    properties:
      response:
        $ref: "#/definitions/response"
  fibonacci_GET_response:
    type: "object"
    required:
    - "result"
    properties:
      result:
        type: "string"
  hello_GET_response:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
  fibonacciasync_GET_response:
    type: "object"
    required:
    - "result"
    properties:
      result:
        type: "string"
  response:
    type: "object"
    required:
    - "transactionId"
    properties:
      transactionId:
        type: "string"
