{
 "title": "APIGW dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "api",
    "label": "api",
    "query": {
     "query": "label_values(sag_apigw_api_tx_count,api_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU consumption",
     "type": "gauge",
     "description": "The number of times the service has executed since the Microservices Runtime last started.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sag_is_server_proc_cpu_percent{product=\"apigw\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Memory consumption",
     "type": "gauge",
     "description": "The number of times the service has executed since the Microservices Runtime last started.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sag_is_used_memory_bytes{product=\"apigw\"} / sag_is_max_memory_bytes{product=\"apigw\"}) * 100",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Disk consumption",
     "type": "gauge",
     "description": "The number of times the service has executed since the Microservices Runtime last started.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sag_is_server_used_disk_mbytes{product=\"apigw\"} / sag_is_server_total_disk_mbytes{product=\"apigw\"}) * 100",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Thread consumption",
     "type": "gauge",
     "description": "The number of times the service has executed since the Microservices Runtime last started.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sag_is_server_threads{product=\"apigw\"} / sag_is_server_maxthreads{product=\"apigw\"}) * 100",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "sag_is_http_requests",
     "type": "timeseries",
     "description": "The total number of HTTP/S requests since the last statistics poll. The statistics poll interval is controlled by the watt.server.stats.pollTime server configuration parameter. The default interval is 60 seconds.\nA request is included in this metric if it calls a top-level service, the service was not canceled, the service is not in a circuit breaker flow step, and the service does not belong to a package listed for the watt.server.stats.packages.exclude server configuration parameter.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sag_is_http_requests{product=\"apigw\"}",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "sag_is_request_starts_per_minute",
     "type": "timeseries",
     "description": "The number of top-level services started each minute.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
     "targets": [
      {
       "expr": "sag_is_request_starts_per_minute{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_total_http_requests",
     "type": "timeseries",
     "description": "The total number of HTTP/S requests since Microservices Runtime startup.\nA request is included in this metric if it calls a top-level service, the service was not canceled, the service is not in a circuit breaker flow step, and the service does not belong to a package listed for the watt.server.stats.packages.exclude server configuration parameter.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "sag_is_total_http_requests{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_service_starts_per_minute",
     "type": "timeseries",
     "description": "The number of top-level services started each minute.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
     "targets": [
      {
       "expr": "sag_is_service_starts_per_minute{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_number_​service_errors",
     "type": "timeseries",
     "description": "The number of service errors since startup, which includes any service that gets an exception of any kind.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sag_is_number_service_errors{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_number_​​service_​errors_per_minute",
     "type": "timeseries",
     "description": "The number of service errors in the last minute.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
     "targets": [
      {
       "expr": "sag_is_number_service_errors_per_minute{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_number_service_invokes",
     "type": "timeseries",
     "description": "The number of successful service invokes and service errors since Microservices Runtime startup. This metric excludes services in a package set in the watt.server.stats.packages.exclude parameter.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
     "targets": [
      {
       "expr": "sag_is_number_service_invokes{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_average_connection_time",
     "type": "timeseries",
     "description": "The running average for the connection time expressed in milliseconds. This can also be described as the average session time or how long a connection is kept alive.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sag_is_average_connection_time{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_number_service_errors_​excluding_internal_svc_​per_minute",
     "type": "timeseries",
     "description": "The number of service errors in the last minute, which includes any service that gets an exception of any kind but excludes any services in a package set in the watt.server.stats.packages.exclude server configuration parameter.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sag_is_number_service_errors_excluding_internal_svc_per_minute{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_number_​nonservice_errors",
     "type": "timeseries",
     "description": "The number of errors that were caused by exceptions that are not ServiceExceptions. This is the same value returned by sag_is_number_unknown_errors.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
     "targets": [
      {
       "expr": "sag_is_number_nonservice_errors{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_number_sessions_used",
     "type": "timeseries",
     "description": "The number of sessions used since Microservices Runtime startup.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
     "targets": [
      {
       "expr": "sag_is_number_sessions_used{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "sag_is_current_stateful_sessions",
     "type": "timeseries",
     "description": "The number of current connections to the Microservices Runtime where the connection is a session which can be created multiple ways such as through an HTTP connection, a trigger, the scheduler, etc.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
     "targets": [
      {
       "expr": "sag_is_current_stateful_sessions{product=\"apigw\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM heap usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sag_is_jvm_memory_heap_used_mbytes{product=\"apigw\"} * 1024 * 1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(sag_is_jvm_memory_pool_max_mbytes{poolType=\"HEAP\", product=\"apigw\"}) * 1024 * 1024",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM non heap usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sag_is_jvm_memory_nonheap_used_mbytes{product=\"apigw\"} * 1024 * 1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(sag_is_jvm_memory_pool_max_mbytes{poolType=\"NON_HEAP\", product=\"apigw\"}) * 1024 * 1024",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(sag_is_jvm_memory_nonheap_used_mbytes{product=\"apigw\"} + sag_is_jvm_memory_heap_used_mbytes{product=\"apigw\"}) * 1024 * 1024",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(sag_is_jvm_memory_pool_max_mbytes{product=\"apigw\"}) * 1024 * 1024",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "JVM thread state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 130 },
     "targets": [
      {
       "expr": "sag_is_jvm_thread_state_timed_waiting_count{product=\"apigw\"}",
       "legendFormat": "timed_waiting"
      },
      {
       "expr": "sag_is_jvm_thread_state_terminated_count{product=\"apigw\"}",
       "legendFormat": "terminated"
      },
      {
       "expr": "sag_is_jvm_thread_state_new_count{product=\"msr\"}",
       "legendFormat": "new"
      },
      {
       "expr": "sag_is_jvm_thread_state_blocked_count{product=\"msr\"}",
       "legendFormat": "blocked"
      },
      {
       "expr": "sag_is_jvm_thread_state_runnable_count{product=\"msr\"}",
       "legendFormat": "runnable"
      },
      {
       "expr": "sag_is_jvm_thread_state_waiting_count{product=\"msr\"}",
       "legendFormat": "waiting"
      }
     ]
    },
    {
     "title": "JVM classes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 130 },
     "targets": [
      {
       "expr": "sag_is_jvm_classes_unloaded_total{product=\"apigw\"}",
       "legendFormat": "unloaded"
      },
      {
       "expr": "sag_is_jvm_classes_loaded_total{product=\"apigw\"}",
       "legendFormat": "loaded"
      },
      {
       "expr": "sag_is_jvm_classes_total{product=\"apigw\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "JVM buffer pool capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sag_is_jvm_memory_buffer_pool_capacity_mbytes{name=\"direct\", product=\"apigw\"} * 1024 * 1024 ",
       "legendFormat": "direct"
      },
      {
       "expr": "sag_is_jvm_memory_buffer_pool_capacity_mbytes{name=\"mapped\", product=\"apigw\"} * 1024 * 1024",
       "legendFormat": "mapped"
      }
     ]
    }
   ]
  },
  { "title": "APIGW server metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "sag_apigw_tx_count",
   "type": "timeseries",
   "description": "Number of aggregated API invocations.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sag_apigw_tx_count{product=\"apigw\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "sag_apigw_apicalls_total",
   "type": "timeseries",
   "description": "Total number of API invocations per response code",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "sag_apigw_apicalls_total{product=\"apigw\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "API metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "sag_apigw_api_tx_count",
   "type": "timeseries",
   "description": "Number of API invocations.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sag_apigw_api_tx_count{api_name=~\"$api\"} ",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "sag_apigw_api_tx_error_count",
   "type": "timeseries",
   "description": "Number of transaction errors",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sag_apigw_api_tx_error_count{api_name=~\"$api\"}",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}