{
 "title": "UM dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "queue",
    "label": "queue",
    "query": {
     "query": "label_values(sag_um_queue_consumed_total{name!~\".*temp.*\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server (realm) metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_um_server_cpu_usage_ratio * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sag_um_server_memory_heap_usage_bytes + sag_um_server_memory_direct_usage_bytes) / (sag_um_server_memory_heap_max_bytes + sag_um_server_memory_direct_max_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sag_um_server_disk_usage_bytes / sag_um_server_disk_total_bytes) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(sag_um_threadpool_idle_threads)",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(sag_um_threadpool_allocated_threads)",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(sag_um_threadpool_stalled_tasks)",
     "legendFormat": "stalled_tasks"
    },
    {
     "expr": "sum(sag_um_threadpool_queued_tasks)",
     "legendFormat": "queued_tasks"
    }
   ]
  },
  {
   "title": "Current connections total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_um_server_currentconnections_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes in",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sag_um_server_bytesin_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bytes out",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sag_um_server_bytesout_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Published messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_um_server_publishedevents_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sag_um_server_consumedevents_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Queue metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "sag_um_queue_published_total",
   "type": "timeseries",
   "description": "Total number of events published on the queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sag_um_queue_published_total{name=~\"destinationName=$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "sag_um_queue_consumed_total",
   "type": "timeseries",
   "description": "Total number of events consumed from the queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sag_um_queue_consumed_total{name=~\"destinationName=$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "sag_um_queue_events_total",
   "type": "timeseries",
   "description": "Total number of events on the queue",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sag_um_queue_events_total{name=~\"destinationName=$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "sag_um_queue_memory_usage_bytes",
   "type": "timeseries",
   "description": "Amount of memory used by the queue in bytes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sag_um_queue_memory_usage_bytes{name=~\"destinationName=$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "sag_um_queue_disk_usage_bytes",
   "type": "timeseries",
   "description": "Current space used by the queue in bytes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sag_um_queue_disk_usage_bytes{name=~\"destinationName=$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "sag_um_queue_currentconnections_total",
   "type": "timeseries",
   "description": "Current number of queue consumers",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sag_um_queue_currentconnections_total{name=~\"destinationName=$queue\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}