services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin 
    volumes:
      - grafana-data-volume:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ../dashboards:/etc/grafana/dashboards

volumes:
  grafana-data-volume: